"""Runtime management utilities.

Functions for runtime ID validation, config fingerprinting, and runtime operations.
"""

import hashlib
import json
import os
import re
import secrets
import sys
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Dict, Iterator, Optional


def validate_uuid_v4(runtime_id: str) -> bool:
    """Validate UUID v4 format for runtime_id.

    Runtime IDs are provided by the caller (Workbench), not generated by CLI.
    This validates the format strictly.

    Args:
        runtime_id: UUID string to validate

    Returns:
        True if valid UUID v4, False otherwise

    Example:
        >>> validate_uuid_v4("550e8400-e29b-41d4-a716-446655440000")
        True
        >>> validate_uuid_v4("rt_a3f9c8e1d4b2f5a7")
        False
    """
    # UUID v4 format: 8-4-4-4-12 hex digits with hyphens
    # Version field (first digit of 3rd group) must be 4
    # Variant field (first digit of 4th group) must be 8, 9, a, or b
    uuid_v4_pattern = re.compile(
        r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$',
        re.IGNORECASE
    )
    return bool(uuid_v4_pattern.match(runtime_id))


def compute_config_fingerprint(
    image: str,
    network: str,
    scope: str,
    workspace: str,
) -> str:
    """Compute deterministic fingerprint of runtime configuration.

    Used for detecting config drift and idempotent retry.
    Returns canonical SHA256 format matching Workbench implementation.

    Args:
        image: Docker image name (e.g., "super-claude:latest")
        network: Network mode ("direct" or "proxy")
        scope: Scope mode ("project" or "temporary")
        workspace: Canonical absolute workspace path

    Returns:
        SHA256 hex digest with 'sha256:' prefix

    Example:
        >>> compute_config_fingerprint(
        ...     "super-claude:latest", "direct", "project", "/home/user/project"
        ... )
        'sha256:a7f3b8c9...'
    """
    # Normalize workspace to canonical path
    canonical_workspace = str(Path(workspace).resolve())

    # Create canonical serialization (must match Workbench)
    config = {
        "image": image,
        "network": network,
        "scope": scope,
        "workspace": canonical_workspace,
    }

    # Use JSON canonical serialization for stability
    config_str = json.dumps(config, sort_keys=True, separators=(',', ':'))

    # Compute full SHA256
    digest = hashlib.sha256(config_str.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


@contextmanager
def workspace_lock(workspace: Path, timeout: float = 10.0) -> Iterator[None]:
    """Acquire exclusive lock on workspace for runtime operations.

    Uses fcntl.flock (Linux/macOS) or msvcrt.locking (Windows).
    Fail-closed: raises on lock acquisition failure.

    Args:
        workspace: Canonical workspace path
        timeout: Lock timeout in seconds

    Raises:
        TimeoutError: If lock cannot be acquired within timeout
        OSError: On other lock-related errors

    Yields:
        None while lock is held
    """
    workspace = workspace.resolve()
    aisc_dir = workspace / ".aisc"
    aisc_dir.mkdir(parents=True, exist_ok=True)
    lock_path = aisc_dir / ".workspace.lock"

    lock_fd = None
    locked = False

    try:
        # Open lock file
        lock_fd = os.open(str(lock_path), os.O_CREAT | os.O_RDWR, 0o644)

        # Platform-specific locking
        if sys.platform == "win32":
            # Windows: msvcrt.locking with blocking
            import msvcrt
            import time

            start_time = time.time()
            while True:
                try:
                    msvcrt.locking(lock_fd, msvcrt.LK_NBLCK, 1)
                    locked = True
                    break
                except OSError:
                    if time.time() - start_time > timeout:
                        raise TimeoutError(
                            f"Failed to acquire workspace lock within {timeout}s"
                        )
                    time.sleep(0.1)
        else:
            # Linux/macOS: fcntl.flock with timeout
            import fcntl
            import signal

            def timeout_handler(signum, frame):
                raise TimeoutError(
                    f"Failed to acquire workspace lock within {timeout}s"
                )

            # Set alarm for timeout
            old_handler = signal.signal(signal.SIGALRM, timeout_handler)
            signal.alarm(int(timeout))

            try:
                fcntl.flock(lock_fd, fcntl.LOCK_EX)
                locked = True
            finally:
                signal.alarm(0)
                signal.signal(signal.SIGALRM, old_handler)

        yield

    finally:
        # Release lock
        if locked and lock_fd is not None:
            try:
                if sys.platform == "win32":
                    import msvcrt
                    msvcrt.locking(lock_fd, msvcrt.LK_UNLCK, 1)
                else:
                    import fcntl
                    fcntl.flock(lock_fd, fcntl.LOCK_UN)
            except OSError:
                pass

        # Close file descriptor
        if lock_fd is not None:
            try:
                os.close(lock_fd)
            except OSError:
                pass
